image: docker:stable

services:
  - docker:dind

build:
  script:
    - docker build --build-arg GITLAB_TOKEN=$GITLAB_TOKEN -t floodlight .
    - docker tag floodlight containers.cisco.com/chart2/floodlight
    - docker push containers.cisco.com/chart2/floodlight